server:
  port: 8880

test:
  hello: "自定义3"
#  HikariPool 较佳配置
hikari:
  connection-timeout: 60000
  validation-timeout: 3000
  idle-timeout: 60000
  login-timeout: 5
  max-lifetime: 60000
  maximum-pool-size: 10
  minimum-idle: 10
  read-only: false
spring:
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms